
name: Set Issues

on:
  push:
    branches:
      - main

jobs:
  SetIssues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Issues
        uses: zlus/action-extract-issues@1.0.0
        id: set_issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          match-reg: 'test +#(\d+)' # optional
          add-labels: enhancement   # optional
          remove-labels: bug        # optional
          add-comment: |            # optional
            already fixed. 

      - name: Log
        run: echo ${{ steps.set_issues.outputs.issues }}
